codecov: do not fail ci on error
Kuadrant/kuadrant-operator pull request #228
Opened 2023-08-10 14:36 UTC by KevFan

* Prevent codecov from failing ci on error due to flakiness with codecov upload

2023-08-10 15:34 UTC, adam-cattermole approved these changes
Looks good to me

2023-08-14 09:29 UTC, art-tapin requested changes
Hey @KevFan! 
The CodeCov uploads the results two times: for unit tests and for integration tests separately. Please, check out the line 90 in test.yaml to change the `true` condition to `false` for integration tests too:
 ```
       - name: Upload integration-test coverage reports to CodeCov # more at https://github.com/codecov/codecov-action
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: integration
          fail_ci_if_error: true
          verbose: true

2023-08-14 10:11 UTC, KevFan commented
Thanks @art-tapin ! Good catch, I've pushed that change just now 👍

2023-08-14 10:59 UTC, art-tapin approved these changes

2023-08-14 11:34 UTC, merged