Install Cert Manager
Kuadrant/kuadrant-operator pull request #258
Opened 2023-09-22 11:05 UTC by Boomatang

Cert manager is required for the webhooks in local deployments.

# Validation 
* run `make local-setup`
* Expected: Installation to complete with a webhook pod running for authorino.
```
kubectl get deployment authorino-webhooks -n kuadrant-system
```

Closes: https://github.com/Kuadrant/kuadrant-operator/issues/257

2023-09-22 11:52 UTC, guicassolato requested changes
Verification steps are all right, but there's a bit more missing here...

Try following the steps of https://docs.kuadrant.io/kuadrant-operator/doc/user-guides/authenticated-rl-for-app-developers all the way 'til having created the AuthPolicy, then:

```sh
kubectl get authconfigs -A
```

and you will get:

```
Error from server: conversion webhook for authorino.kuadrant.io/v1beta1, Kind=AuthConfig failed: Post "https://authorino-webhooks.kuadrant-system.svc:443/convert?timeout=30s": tls: failed to verify certificate: x509: certificate is valid for authorino-webhooks.authorino-operator.svc, authorino-webhooks.authorino-operator.svc.cluster.local, not authorino-webhooks.kuadrant-system.svc
```

<br/>

We need: https://github.com/Kuadrant/kuadrant-operator/pull/256/files#diff-5cf7dccb6f66d96ec7ca61d40919985a8d7ed1025572ef5a8868c12615406639

(...which should not be part of my PR IMO, but to this one though.)

2023-09-25 10:59 UTC, Boomatang commented
@guicassolato Thanks for that. I have included the changes that you linked to. 

The interesting thing that I have found out is k9s works differently to kubectl when listing resources.  K9s had no issues and this confused me as I felt it was working on my machine.

2023-09-25 13:34 UTC, KevFan approved these changes
Changes looks good to me 👍 

<img width="938" alt="image" src="https://github.com/Kuadrant/kuadrant-operator/assets/24636860/bbc61a23-1214-4164-b5ce-3c05a096af16">

2023-09-27 09:22 UTC, guicassolato approved these changes
Perfect, @Boomatang! Thank you!

2023-09-27 09:29 UTC, merged