Object types
Kuadrant/kuadrant-operator pull request #777
Opened 2024-07-23 15:56 UTC by eguzki

2024-07-23 20:45 UTC, eguzki commented
@Boomatang I would appreciate your :eyes: on this PR :bowing_man:

2024-07-24 14:45 UTC, Boomatang reviewed
I see what is being done and kinda why it is being done. What I am concerned about is the adding of yet more interfaces and structs that we need to be aware of. 

My mind is in two places over wide interfaces compared to deep interfaces. What is your view on the abstraction and abstracting to early?

2024-07-26 09:51 UTC, eguzki commented
> I see what is being done and kinda why it is being done. What I am concerned about is the adding of yet more interfaces and structs that we need to be aware of.
> 
> My mind is in two places over wide interfaces compared to deep interfaces. What is your view on the abstraction and abstracting to early?

I plan to  write common (reusable) controller mappers and generic (reusable) controllers that can be used by any policy type. This is kind of preparation work for it.

2024-07-26 14:10 UTC, Boomatang requested changes
Looks good to me and is a good stepping stone to something better

2024-07-26 14:41 UTC, merged