Issues/730
Kuadrant/kuadrant-operator pull request #994
Opened 2024-11-08 15:39 UTC by KevFan

2025-01-08 14:56 UTC, Boomatang commented
I think there is some improvement needed here. Firstly I rebased this to current main, and everything worked as expected. 

The simpler issue is around the message in the status block `Limitador Operator is not installed, please restart pod once dependency has been installed`. When I first seen this message I ask what pod do I restart. I think we need to be clear that it is the kuadrant operator that the user should restart. This might not be as important for the kuadrant CR directly, but on the policy CR's I think it is need.

The second issue is are clarity, but raises its own issue. Doing the example above the kuadrant CR states that Limitador Operator is missing, but all the resources are missing. The user would fix one issue, restart the operator only to find the next issue. Where they would have to repeat the process over and over. This is not great. I think we should be telling the user all the dependencies that are missing at the same time. 

The third point and I don't think it is an issue but more of an opportunity. When I tried the example give, at first I didn't make every CR type, I only made the one for auth. As a user the only on thing I am currently using kuadrant for is auth. Why do I care if limitador and DNS operators are not working.  Wouldn't it be nice if kuadrant only told you had a dependency issue if you apply resources to the cluster that depends on that dependency. I also think this could help us on the part of solving this issue: https://github.com/Kuadrant/kuadrant-operator/issues/71

While I am at it I think we might need more log level than info & error for production. I think there needs to be a warning level. 
```
{"level":"info","ts":"2025-01-08T14:21:52Z","logger":"kuadrant-operator","msg":"envoygateway is not installed, skipping related watches and reconcilers","err":null}
```
The above message is from the logs in pr, and I think it should be a warning over info level log. This possible is out side the scope of this PR, but it is a good example of what would be a warning.

One last point, which is splitting hairs, technically the `Limitador Operator is not installed` is wrong. It is the limitador CRD that is not installed. Do we want to get that fine grained, I don't think so.

2025-01-09 11:44 UTC, KevFan commented
> The simpler issue is around the message in the status block `Limitador Operator is not installed, please restart pod once dependency has been installed`. When I first seen this message I ask what pod do I restart. I think we need to be clear that it is the kuadrant operator that the user should restart. This might not be as important for the kuadrant CR directly, but on the policy CR's I think it is need.
>
I think this is a good shout. Are we thinking of just calling it "Kuadrant Operator pod"? I assume this is alright for the downstream also 🤔 
 
> The second issue is are clarity, but raises its own issue. Doing the example above the kuadrant CR states that Limitador Operator is missing, but all the resources are missing. The user would fix one issue, restart the operator only to find the next issue. Where they would have to repeat the process over and over. This is not great. I think we should be telling the user all the dependencies that are missing at the same time.
> 
Yeah, this makes sense 👍 

> The third point and I don't think it is an issue but more of an opportunity. When I tried the example give, at first I didn't make every CR type, I only made the one for auth. As a user the only on thing I am currently using kuadrant for is auth. Why do I care if limitador and DNS operators are not working. Wouldn't it be nice if kuadrant only told you had a dependency issue if you apply resources to the cluster that depends on that dependency. I also think this could help us on the part of solving this issue: #71
> 
This one, I'm not sure I understand the scenario you are saying. If you are doing Auth only, this missing dependency will only be reported in Kuadrant and AuthPolicy CR status. If you didn't apply Kuadrant CR, then it will be reported in AuthPolicy CR status only. Kuadrant CR cares about limitador and authorino since it creates an instance of those CRs. The current changes should already provide what you are saying - CRs that kuadrant provide should only report missing dependencies that each CR depend on - unless I'm missing something and you are saying this is not the case 🤔 

> While I am at it I think we might need more log level than info & error for production. I think there needs to be a warning level.
> 
> ```
> {"level":"info","ts":"2025-01-08T14:21:52Z","logger":"kuadrant-operator","msg":"envoygateway is not installed, skipping related watches and reconcilers","err":null}
> ```
> 
> The above message is from the logs in pr, and I think it should be a warning over info level log. This possible is out side the scope of this PR, but it is a good example of what would be a warning.
> 
This would be outside of scope for sure. I don't believe the logger that we use even has a `warning` log type currently.

> One last point, which is splitting hairs, technically the `Limitador Operator is not installed` is wrong. It is the limitador CRD that is not installed. Do we want to get that fine grained, I don't think so.

This is true, I don't think we want to be that fine grained. Might be able to improve this seperately, but outside of scope for this PR I would say. Kuadrant depends more on the CRD but would also have issues if the Operator is not running. Since we generally report status based on the status of the dependant CRs, I think we indicate something is unexepcted from the environment as our CR status will never go into a `Ready/Enforced` state 🤔 I can rename if that is our general preference everywhere. Will be a seperate issue/PR though.

2025-01-13 09:49 UTC, Boomatang commented
>>The third point and I don't think it is an issue but more of an opportunity. When I tried the example give, at first I didn't make every CR type, I only made the one for auth. As a user the only on thing I am currently using kuadrant for is auth. Why do I care if limitador and DNS operators are not working. Wouldn't it be nice if kuadrant only told you had a dependency issue if you apply resources to the cluster that depends on that dependency. I also think this could help us on the part of solving this issue: https://github.com/Kuadrant/kuadrant-operator/issues/71
>
>This one, I'm not sure I understand the scenario you are saying. If you are doing Auth only, this missing dependency will only be reported in Kuadrant and AuthPolicy CR status. If you didn't apply Kuadrant CR, then it will be reported in AuthPolicy CR status only. Kuadrant CR cares about limitador and authorino since it creates an instance of those CRs. The current changes should already provide what you are saying - CRs that kuadrant provide should only report missing dependencies that each CR depend on - unless I'm missing something and you are saying this is not the case 🤔

Okay what i was meaning is the kuadrant CR only gave an error related to Limitador and no error related to authorino. Authorino was what I was trying to use. The issue really is the kuadrant CR status will only list one error at a time. I the case that I looked at the user would have seen the limitador error fixed that error, and restarted kuadrant to only find out there was more errors. If there is more than one error these errors need to be list at the same time.

2025-01-15 16:01 UTC, Boomatang requested changes
I have one nit pick around the exit logging statement and few questions around styling that you might change. 

Every thing is working as expected, and I think the messaging is much better now.

2025-01-15 16:49 UTC, KevFan commented on controllers/state_of_the_world.go
> +	var err error
I think this is a workaround from the following Goland IDE error:

![image](https://github.com/user-attachments/assets/6f2b51d0-ded3-4225-846f-1f8dd279eb4e)

whereas this would work if doing:

![image](https://github.com/user-attachments/assets/2942894f-0a41-4198-9463-85625fbf286b)

Seems its not possible (at least according to Goland IDE) to assign the bool to a struct field **and** initialize a new variable. The actions must be the same (both initialised or both re-assigned) for the multiple variables returned 🤔 

I can do:

```go
	installed, err := utils.IsCRDInstalled(b.manager.GetRESTMapper(), DNSRecordGroupKind.Group, DNSRecordGroupKind.Kind, kuadrantdnsv1alpha1.GroupVersion.Version)
        b.isDNSOperatorInstalled = installed 
```

If that is the preference?

2025-01-15 16:53 UTC, KevFan commented on controllers/state_of_the_world.go
> +		b.logger.Info("dns operator is not installed, skipping related watches and reconcilers", "err", err)
Sounds good 👍

2025-01-15 17:04 UTC, KevFan commented on controllers/state_of_the_world.go
> +		Postcondition: finalStepsWorkflow(b.client, b.isGatewayAPIInstalled, b.isIstioInstalled, b.isEnvoyGatewayInstalled).Run,
Yes, agreed, I don't quite like this. I had an initial thought of potentially separating the dependencies flags in `BootOptionsBuilder` into it's own struct:

```go
type BootOptionsBuilder struct {
	logger  logr.Logger
	manager ctrlruntime.Manager
	client  *dynamic.DynamicClient
	dependencies *Dependencies 
}

type Dependencies struct {
	// Internal configurations
	isGatewayAPIInstalled        bool
	isEnvoyGatewayInstalled      bool
	isIstioInstalled             bool
	isCertManagerInstalled       bool
	isConsolePluginInstalled     bool
	isDNSOperatorInstalled       bool
	isLimitadorOperatorInstalled bool
	isAuthorinoOperatorInstalled bool
}
```

And potentially just pass this into the subsequent reconcilers that require this information. Granted just doing this, would leak unnecessary info to respective reconcilers (e.g. auth would not care about limitador for reporting). 

What's your thoughts?

2025-01-15 17:09 UTC, KevFan commented on pkg/authorino/conditions.go
> +}
Hmm, still probably better to still log all the missing CRDs but yes, we do not use/report the error in the CR status

2025-01-16 12:12 UTC, Boomatang commented on controllers/state_of_the_world.go
> +	var err error
I think we leave it as it is. If at some point we want to change it there is more than just here to change it.

2025-01-16 12:33 UTC, Boomatang commented on controllers/state_of_the_world.go
> +		Postcondition: finalStepsWorkflow(b.client, b.isGatewayAPIInstalled, b.isIstioInstalled, b.isEnvoyGatewayInstalled).Run,
I was thinking about this, and I am wondering what `map[string]bool` would be like. It would remove the leaking of unnecessary information to the respective reconcilers. How they are created that I am not sure.

2025-01-17 09:54 UTC, Boomatang approved these changes
I am happy with how this is working now. There was that on debug log that we talked about. If you want to change that here, I am happy to look at it again.

2025-01-20 10:20 UTC, merged

2025-01-20 10:34 UTC, KevFan commented on pkg/authorino/conditions.go
> +}
Created https://github.com/Kuadrant/kuadrant-operator/issues/1127 for this enhancement

2025-01-20 10:50 UTC, KevFan commented on controllers/state_of_the_world.go
> +		Postcondition: finalStepsWorkflow(b.client, b.isGatewayAPIInstalled, b.isIstioInstalled, b.isEnvoyGatewayInstalled).Run,
Created https://github.com/Kuadrant/kuadrant-operator/issues/1128 to track this enhancement